### ISSUE TITLE
Make explicit the required torch version

### ISSUE THREAD

**Issue by mrtj** [kwwendt/sagemaker-yolov4-e2e-example#1]
I tried to run the notebook with pytorch version 1.4 (the version that can be found by default on SageMaker notebooks) and version 1.7. The first attempt failed because it could not load the SageMaker trained yolo model, because the model version was more recent than my actual torch version. Running the notebook with torch v1.7 traced successfully the model but this time the Neo compilation job failed with a somehow cryptic error saying:

```
ClientError: InputConfiguration: Framework cannot load PyTorch model. 

aten::_convolution(Tensor input, Tensor weight, Tensor? bias, int[] stride, int[] padding, int[] dilation, bool transposed, int[] output_padding, int groups, bool benchmark, bool deterministic, bool cudnn_enabled) -> (Tensor):
Expected at most 12 arguments but found 13 positional arguments.
...
def forward(self: __torch__.torch.nn.modules.conv.Conv2d, input: Tensor) -> Tensor: 
input0 = torch._convolution(input, self.weight, None, [1, 1], [1, 1], [1, 1], False, [0, 0], 1, False, False, True, True)
~~~~~~~~~~~~~~~~~~ <--- HERE\n return input0
```

After some research, I figured out that it's due to the mismatching framework version between pytorch that created the traced model and pytorch in the Neo compilation job container, later is calling the torchscript executable with the "wrong" number of arguments.

At last I figured out that if I run the notebook and trace the model with pytorch v1.6, it works well, and creates a traced model that can be consumed by the Neo compilation job. I guess the `framework_version` should be specified also to `1.6` (instead of `1.7`) in the notebook, as it is the only version [supported by Neo](https://docs.aws.amazon.com/sagemaker/latest/dg/neo-supported-devices-edge-frameworks.html) and even if you specify 1.7, indeed internally it uses 1.6.

**Comment by kwwendt** [comment]
Hi! Thank you for raising this issue. You are correct, this was a mistake on my part and I have corrected the issue with the latest merge. Please let me know if you face further issues with the notebook.

Please note: I am still working on getting the compiled model to work with SageMaker hosting. Right now the non-optimized model is being used in the hosting step for inference.
